name: CoVasc_App
channels: 
  - conda-forge
dependencies:
  - pip
  - python
  - pip:
      - numpy
      - pandas
      - scikit-image
      - pillow
      - openpyxl
      - streamlit
      - pydeck
      - plotly
