name: CoVasc_App

dependencies:
  - pip
  - python
  - plotly
  - pip:
      - numpy
      - pandas
      - scikit-image
      - pillow
      - openpyxl
      - streamlit
      - pydeck
