name: CoVasc_App
dependencies:
  - pip
  - python
  - pip:
    - numpy
    - pandas
    - scikit-image
    - pillow
    - openpyxl
    - streamlit
    - pydeck
    - plotly
    - nbserverproxy
    - streamlit
    - jupyter-server-proxy

