name: CoVasc_App
channels:
  - conda
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter-server-proxy
  - pip:
    - numpy
    - pandas
    - scikit-image
    - pillow
    - openpyxl
    - streamlit
    - pydeck
    - plotly
    - streamlit

